version: "3"
services:
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
  hive:
    build: hive
    ports:
      - ${PORT:-9083}:9083
    environment:
      - DB_URI=mariadb:3306
      - S3A_ENDPOINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - mariadb
  lakectl:
    image: treeverse/lakectl:metastore3
    volumes:
      - ./lakectl.yaml:/home/lakefs/.lakectl.yaml

